language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

# If there ever comes a need in the future:
# command to install dependencies
#install: 
# - pip install -r requirements.txt
 
# command to run tests
script:
 - make test
 